### ISSUE TITLE
error after updating the leaflet and react-leaflet

### ISSUE THREAD

**Issue by niksinfinite10** [alex3165/react-leaflet-draw#11]
I am getting `this.leafletElement.removeFrom is not a function` error after updating the latest version of react-leaflet and leaflet in my project.

**Comment by alex3165** [comment]
Hey @niksinfinite10 I am on it : https://github.com/alex3165/react-leaflet-draw/pull/12 the delete feature is broken for now, once it is fixed I will merge it

**Comment by thewazir** [comment]
Hey @alex3165 is there anything I can do to help fix this error?

**Comment by alex3165** [comment]
Hey @thewazir, you can have a look at https://github.com/alex3165/react-leaflet-draw/pull/12/files deleting a shape doesn't work that's the only issue before merging it

**Comment by alex3165** [comment]
The PR has been merged and I have released a new version `0.11` of `react-leaflet-draw` it should be fixed. Let me know if it's good then I can close this issue

**Comment by CBMasri** [comment]
Hey @alex3165, thanks for the update! The error was still occurring for me, but changing `this.leafletElement.removeFrom(map)` to `this.leafletElement.remove(map)` works (apparently `drawControl` has no `removeFrom(map)`, just `drawControl.remove(map)`.

**Comment by alex3165** [comment]
@CBMasri I am happy to merge a PR with the changes if you are up to.
